<?php

namespace okazo\geoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * countryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class countryRepository extends EntityRepository
{
}
