imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: facebookParameters.ini }
    - { resource: websiteParameters.ini }
    
services:
    my.facebook.user:
        class: okazo\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            #container: "@service_container"
    #Service pour transmettre la _locale utilisée dans tout le projet
    okazo_locale.locale_listener:
        class: okazo\MainBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    #Service pour ajouter un mot clé Twig, permettant d'accéder aux paramètres stockés en base de donnée
    okazo.twig.okazo_extension:
        class: okazo\MainBundle\Twig\okazoTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%    
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%    
    session:         ~        

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:        
        websiteName:                %websiteName%
        websiteSlogan:              %websiteSlogan%
        websiteBirthYear:           %websiteBirthYear%
        websiteShowHeader:          %websiteShowHeader%
        websiteShowLogin:           %websiteShowLogin%
        websiteShowLanguageChooser: %websiteShowLanguageChooser%
        websiteUseFacebookLogin:    %websiteUseFacebookLogin%
        websiteUseInternalLogin:    %websiteUseInternalLogin%
        facebookLocale:             %facebookLocale%
        facebookAppID:              %facebookAppID%
        websiteUseGoogleAnalytics:  %websiteUseGoogleAnalytics%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    java: C:\\Program Files (x86)\\Java\\jre7\\bin\\java.exe
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor/yuicompressor-2.4.7.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            numeric_functions:
                GEO_DISTANCE:                okazo\geoBundle\Doctrine\Query\Mysql\GeoDistance
                GEO_DISTANCE_BY_POSTAL_CODE: okazo\geoBundle\Doctrine\Query\Mysql\GeoDistanceByPostalCode

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    port:       %mailer_port%
    encryption: %mailer_encryption%
    username:   %mailer_user%
    password:   %mailer_password%
    #spool:     { type: memory }
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: okazo\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false    #true for email confirmation when creating an account
    from_email:
        address: contact@okazo.eu
        sender_name: Okazo
    
fos_facebook:
      #file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
      alias:  facebook
      app_id: %facebookAppId%
      secret: %facebookAppSecret%
      cookie: true
      permissions: [email]    
