imports:    
    - { resource: facebookParameters.ini }

security:
    #factories:
    #    - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]                    
        my_fos_facebook_provider:
            id: my.facebook.user            
        fos_userbundle:            
            #id: fos_user.user_provider.username      #login via pseudo
            id: fos_user.user_provider.username_email #login via pseudo or email
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: %facebookAppUrl%
                server_url: %facebookServerUrl%
                login_path: /login
                check_path: /login_fb_check
                default_target_path: /
                provider: my_fos_facebook_provider
            logout:
                true
                #handlers: ["fos_facebook.logout_handler"]
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_USER       : ROLE_USER
        ROLE_FACEBOOK   : ROLE_USER
        ROLE_ADMIN      : ROLE_ADMIN, ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER
        ROLE_TEST: ROLE_USER
        ROLE_TEST2: ROLE_USER
        ROLE_TEST3: [ROLE_TEST2]