indexAdmin:
  path: /
  defaults: { _controller: okazoMainBundle:admin:indexAdmin }
  
blockUserAdmin:  
  path: /blocks/userAdmin
  defaults: { _controller: okazoMainBundle:admin:blockUserAdmin }
  
blockAdsAdmin:  
  path: /blocks/adsAdmin
  defaults: { _controller: okazoMainBundle:admin:blockAdsAdmin}
  
adminClearCache:
  path: /clearCache
  defaults: { _controller: okazoMainBundle:admin:ClearCache }
  
testMail:
  path: /testMail
  defaults: { _controller: okazoMainBundle:admin:testMail }