parameters:
    okazoannonces.class: okazo\annoncesBundle\Services\annonces
    okazoparameters.class: okazo\MainBundle\Services\parameters

services:
    okazo.annonces:
        class: %okazoannonces.class%
        arguments: [%okazo.usersMediaPath%, %kernel.root_dir%, @doctrine.orm.entity_manager]
        public: true
        
    okazo.parameters:
        class: %okazoparameters.class%
        arguments: [@doctrine.dbal.default_connection]
        public: true
            
