<?php

namespace okazo\logBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logRepository extends EntityRepository
{
}
