<?php

namespace okazo\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * parametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parametersRepository extends EntityRepository
{
}
