services:
    sonata.admin.okazo.users:
        class: okazo\UserBundle\Admin\userAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Utilisateurs" }
        arguments:
            - ~
            - okazo\UserBundle\Entity\user
            - ~
        calls:
            - [ setTranslationDomain, [okazoUserBundle]]    